development:
  adapter: postgresql
  encoding: unicode
  database: Collaboration_development
  pool: 5
  username: neeraj
  password: neerajneha30may

test:
  adapter: postgresql
  encoding: unicode
  database: Collaboration_test
  pool: 5
  username: neeraj
  password: neerajneha30may

production:
  adapter: postgresql
  encoding: unicode
  database: Collaboration_production
  pool: 5
  username: neeraj
  password: neerajneha30may